window.muzik = {
  repeat_mode: 0, // 1 = all, 2 = one
  track_keypress: true,
  $artist: document.getElementById("artist"),
  $artwork: document.getElementById("artwork"),
  $colors: document.getElementById("colors"),
  $muted: document.getElementById("muted"),
  $next: document.getElementById("next"),
  $pause: document.getElementById("pause"),
  $play: document.getElementById("play"),
  $playlistList: document.getElementById("playlist-list"),
  $playlistWrapper: document.getElementById("playlist-wrapper"),
  $previous: document.getElementById("previous"),
  $repeat: document.getElementById("repeat"),
  $repeat1: document.getElementById("repeat1"),
  $searchField: document.getElementById("search-field"),
  $shuffle: document.getElementById("shuffle"),
  $themeColor: document.getElementById("theme-color"),
  $timeCurrent: document.getElementById("time-current"),
  $timestamp: document.getElementById("timestamp"),
  $timeTotal: document.getElementById("time-total"),
  $title: document.getElementById("title"),
  $video: document.getElementById("video"),
  $volume: document.getElementById("volume"),
  $volumeRange: document.getElementById("volume-range"),
  $volumeWrapper: document.getElementById("volume-wrapper"),
};
